# externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-db-creds-aws
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: postgres-db-creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: DB_CREDS
  - extract:
      key: PG_CREDS

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-rabbitmq-creds-aws
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: rabbitmq-creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rabbitmq-creds-aws
