# secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        # jwt:
        #   serviceAccountRef:
        #     name: default
        secretRef: 
          accessKeyIDSecretRef:
            name: aws-secret-store
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret-store
            key: secret-access-key