apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: barista-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: barista
  minReplicas: {{ .Values.barista.hpa.minReplicas }}
  maxReplicas: {{ .Values.barista.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ .Values.barista.hpa.metrics.resource.name }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.barista.hpa.metrics.resource.target.averageUtilization }}
