apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
type: Opaque
data:
  # RABBITMQ_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzIvCg==
  # RABBITMQ_DEFAULT_USER: Z3Vlc3QK
  # RABBITMQ_DEFAULT_PASS: Z3Vlc3QK
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=