apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter
  minReplicas: {{ .Values.counter.hpa.minReplicas }}
  maxReplicas: {{ .Values.counter.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ .Values.counter.hpa.metrics.resource.name }}
        target:
          type: {{ .Values.counter.hpa.metrics.resource.target.type }}
          averageUtilization: {{ .Values.counter.hpa.metrics.resource.target.averageUtilization }}
