name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Pull images
      run: |
        docker pull cuongopswat/go-coffeeshop-web
        docker pull cuongopswat/go-coffeeshop-barista
        docker pull cuongopswat/go-coffeeshop-counter
        docker pull cuongopswat/go-coffeeshop-product
        docker pull cuongopswat/go-coffeeshop-proxy
        docker pull cuongopswat/go-coffeeshop-kitchen
        
        
    
    - name: Cache Trivy DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy  # Cache path for Trivy DB
        key: ${{ runner.os }}-trivy-db
        restore-keys: |
          ${{ runner.os }}-trivy-db

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Scan image by Trivy
      run: |
        # # trivy image cuongopswat/go-coffeeshop-web --severity CRITICAL  #--exit-code 1
        # trivy image cuongopswat/go-coffeeshop-barista --severity CRITICAL #--exit-code 1
        # trivy image cuongopswat/go-coffeeshop-counter --severity CRITICAL #--exit-code 1
        # trivy image cuongopswat/go-coffeeshop-product --severity CRITICAL #--exit-code 1
        # trivy image cuongopswat/go-coffeeshop-proxy --severity CRITICAL #--exit-code 1
        # trivy image cuongopswat/go-coffeeshop-kitchen --severity CRITICAL #--exit-code 1

        trivy image cuongopswat/go-coffeeshop-web --severity CRITICAL --format json > trivy_report.json
        trivy image cuongopswat/go-coffeeshop-barista --severity CRITICAL --format json >> trivy_report.json
        trivy image cuongopswat/go-coffeeshop-counter --severity CRITICAL --format json >> trivy_report.json
        trivy image cuongopswat/go-coffeeshop-product --severity CRITICAL --format json >> trivy_report.json
        trivy image cuongopswat/go-coffeeshop-proxy --severity CRITICAL --format json >> trivy_report.json
        trivy image cuongopswat/go-coffeeshop-kitchen --severity CRITICAL --format json >> trivy_report.json
        
    - name: Send email with Trivy report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}  # Add this as a secret in GitHub
        password: ${{ secrets.SMTP_PASSWORD }}  # Add this as a secret in GitHub
        from: ${{ secrets.SMTP_USERNAME }}
        to: recipient@example.com  # Change this to the recipient's email
        subject: Trivy Security Scan Report
        body: |
          The Trivy security scan has completed. Please find the attached report.
        attachments: trivy_report.json
