apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-shell
  template:
    metadata:
      labels:
        app: alpine-shell
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 3600000"]
        tty: true
